jobs:
  mirror_to_org:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to other repo'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:UniqueCodeGit/UniquecodeWeb.git
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
    if: github.repository_owner == 'pikokr'
on:
  - push
